### ISSUE TITLE
SSR authentication sample.

### ISSUE THREAD

**Issue by pandarun** [rbanks54/vue-and-identityserver#2]
Thank you for your sample!

Have you tried to implement server side rendering with vuejs / identity server?

What flow would you choose for axios client requests and axios server requests from nodejs?

How to properly store and refresh tokens?

Thanks in advance.

**Comment by rbanks54** [comment]
I haven't actually used SSR approaches at this point, so I'm just theorising.

Also, i you're using SSR for SEO purposes, or so you can content cards for twitter, etc, I suspect you probably don't need to worry about authenticated API calls. Would you be rendering authenticated content for bots to crawl?

Assuming you still want to SSR because of performance reasons, then consider that SSR is conceptually just rendering (most of) a page on a server. Your server is effectively just a headless browser and should call your back end APIs in exactly the same way a client browser would.

In your app, your users would sign in and get an auth token as per usual. WHen you then call the SSR end points, just make sure you include the Bearer auth token. Your SSR code can reuse that token in any calls made to the back end API. The trick is to ensure that your SSR code uses the same OIDC client ID information that is used when the code is running in the browser.

Does that make sense?

**Comment by pandarun** [comment]
Thanks!

I've managed to get authenticated SSR working with IdentityServer and [hybrid flow.](https://leastprivilege.com/2019/01/18/an-alternative-way-to-secure-spas-with-asp-net-core-openid-connect-oauth-2-0-and-proxykit/). Not Implicit you mentioned.
